// clk_100.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module clk_100 (
		input  wire  in_clk,    //    in_clk.clk
		output wire  out_clk,   //   out_clk.clk
		output wire  out_clk_1  // out_clk_1.clk
	);

	assign out_clk = in_clk;

	assign out_clk_1 = in_clk;

endmodule
