// clock_bridge_0.v

// Generated using ACDS version 18.1 221

`timescale 1 ps / 1 ps
module clock_bridge_0 (
		input  wire  in_clk,  //  in_clk.clk
		output wire  out_clk  // out_clk.clk
	);

	assign out_clk = in_clk;

endmodule
