// rst_in.v

// Generated using ACDS version 18.1 222

`timescale 1 ps / 1 ps
module rst_in (
		input  wire  clk,         //       clk.clk
		input  wire  in_reset_n,  //  in_reset.reset_n
		output wire  out_reset_n  // out_reset.reset_n
	);

	assign out_reset_n = in_reset_n;

endmodule
